<a href="https://colab.research.google.com/github/hwayoungc24-rgb/younghwa/blob/main/titanic1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np
import pandas as pd

In [37]:
import pandas as pd
from google.colab import drive


drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/titanic.csv")

df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [38]:
# 결측치 확인
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [39]:
# 3. 결측치 제거
# age 컬럼의 결측치 평균값으로 대체
mean_age = df['Age'].mean()
df.fillna({'Age': mean_age}, inplace=True)

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

In [40]:
# 결측치 제거
df = df.dropna()
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [41]:
# 4. 레이블 확인
df['Survived'].value_counts()

Survived
1    134
0     68
Name: count, dtype: int64

In [42]:
# 5. 불필요한 컬럼 제거
df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin', 'Embarked'], inplace=True)

df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare
1           1       1  female  38.0      1      0  71.2833
3           1       1  female  35.0      1      0  53.1000
6           0       1    male  54.0      0      0  51.8625
10          1       3  female   4.0      1      1  16.7000
11          1       1  female  58.0      0      0  26.5500
..        ...     ...     ...   ...    ...    ...      ...
871         1       1  female  47.0      1      1  52.5542
872         0       1    male  33.0      0      0   5.0000
879         1       1  female  56.0      0      1  83.1583
887         1       1  female  19.0      0      0  30.0000
889         1       1    male  26.0      0      0  30.0000

[202 rows x 7 columns]

In [43]:
# 변환 전
df['Sex'].value_counts()

Sex
male      107
female     95
Name: count, dtype: int64

In [44]:
# 6. encoding
# LabelEncoder 초기화
label_encoder = LabelEncoder() # 문자형 데이터를 숫자로 변환 (범주형 데이터 -> 정수)

# 특정 컬럼만 인코딩
columns_to_encode = ['Sex']

for column in columns_to_encode:
    df[column] = label_encoder.fit_transform(df[column])

df

     Survived  Pclass  Sex   Age  SibSp  Parch     Fare
1           1       1    0  38.0      1      0  71.2833
3           1       1    0  35.0      1      0  53.1000
6           0       1    1  54.0      0      0  51.8625
10          1       3    0   4.0      1      1  16.7000
11          1       1    0  58.0      0      0  26.5500
..        ...     ...  ...   ...    ...    ...      ...
871         1       1    0  47.0      1      1  52.5542
872         0       1    1  33.0      0      0   5.0000
879         1       1    0  56.0      0      1  83.1583
887         1       1    0  19.0      0      0  30.0000
889         1       1    1  26.0      0      0  30.0000

[202 rows x 7 columns]

In [45]:
# 변환 후
df['Sex'].value_counts()

Sex
1    107
0     95
Name: count, dtype: int64

In [46]:
# 데이터 분할
X = df.drop(columns=['Survived']) # X = df.drop('Survived', axis=1)
y = df['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [55]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [56]:
# 랜덤 포레스트 학습 및 평가
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_pred)

print(f"Random Forest Accuracy: {rf_accuracy:.4f}")
print("Confusion Matrix:")
print(confusion_matrix(y_test, rf_pred))

Random Forest Accuracy: 0.8293
Confusion Matrix:
[[ 5  3]
 [ 4 29]]

In [57]:
# 결정 트리 학습 및 평가
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)
dt_accuracy = accuracy_score(y_test, dt_pred)

print(f"Decision Tree Accuracy: {dt_accuracy:.4f}")
print("Confusion Matrix:")
print(confusion_matrix(y_test, dt_pred))

Decision Tree Accuracy: 0.8293
Confusion Matrix:
[[ 3  5]
 [ 2 31]]

In [58]:
# 로지스틱 회귀 학습 및 평가
lr_model = LogisticRegression(max_iter=200)
lr_model.fit(X_train, y_train)
lr_pred = lr_model.predict(X_test)
lr_accuracy = accuracy_score(y_test, lr_pred)

print(f"Logistic Regression Accuracy: {lr_accuracy:.4f}")
print("Confusion Matrix:")
print(confusion_matrix(y_test, lr_pred))

Logistic Regression Accuracy: 0.7561
Confusion Matrix:
[[ 5  3]
 [ 7 26]]

In [59]:
# KNN 학습 및 평가
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)
knn_pred = knn_model.predict(X_test)
knn_accuracy = accuracy_score(y_test, knn_pred)

print(f"KNN Model Accuracy: {knn_accuracy:.4f}")
print("Confusion Matrix:")
print(confusion_matrix(y_test, knn_pred))

KNN Model Accuracy: 0.7805
Confusion Matrix:
[[ 4  4]
 [ 5 28]]

In [25]:
X=df.drop('Survived',axis=1)
X.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

In [26]:
y=df['Survived']
y.value_counts()

Survived
1    123
0     60
Name: count, dtype: int64

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [28]:
print(X_train.columns)

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [29]:
df = df.drop(columns=['Name','Ticket','Cabin'], errors='ignore')

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))

ValueError: could not convert string to float: 'Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")'

In [34]:
# Build a decision tree classifier and predict

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))

ValueError: could not convert string to float: 'Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")'

In [35]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))

--- Radom Forest ---

ValueError: could not convert string to float: 'Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")'